services:
  postgres:
    image: postgres:17

    restart: unless-stopped

    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=DM8JXS5LSr24FLKd
      - POSTGRES_PASSWORD=Se9zhnPod9EKw47Z
    ports:
      - 127.0.0.1:54331:5432
    command: -c 'max_connections=2000'
    volumes:
      - ./src/postgresql:/var/lib/postgresql/data/pgdata
